allow prefix matching for incomplete identifier
pgmoneta/pgmoneta pull request #113
Opened 2023-03-14 07:10 UTC by Jubilee101

If an identifier cannot be found, try matching prefix of existing backups

2023-03-14 09:20 UTC, jesperpedersen requested changes

2023-03-14 09:20 UTC, jesperpedersen commented on src/libpgmoneta/wf_restore.c
> +       if (pgmoneta_get_backups(root, &number_of_backups, &backups))
Indent by 3

2023-03-14 15:12 UTC, Jubilee101 commented
I think I fixed it. Not entirely sure though. Let me know if there's problem.

2023-03-15 05:36 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

2023-03-15 05:36 UTC, closed without merging