[#107] Use pgmoneta_append instead of sprintf in AWS and Azure storage engines
pgmoneta/pgmoneta pull request #119
Opened 2023-04-25 16:24 UTC by MariamFahmy98

Using pgmoneta_append instead of sprintf in AWS and Azure storage engines.

2023-04-26 05:58 UTC, jesperpedersen requested changes

2023-04-26 05:58 UTC, jesperpedersen commented on src/libpgmoneta/se_azure.c
> +      pgmoneta_append(string_to_sign, "PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-blob-type:BlockBlob\nx-ms-date:");
Please, use the full signature

```
string_to_sign = pgmoneta_append(string_to_sign, ...);

2023-05-02 14:37 UTC, jesperpedersen commented
@MariamFahmy98 Could you get this sorted, please

2023-05-18 12:32 UTC, jesperpedersen commented
@MariamFahmy98 ^

2023-06-03 14:14 UTC, jesperpedersen commented
@MariamFahmy98 ping ?

2023-06-03 22:19 UTC, MariamFahmy98 commented
I apologize for being late. Let me know if you have any comments on this PR.

2023-06-05 11:40 UTC, jesperpedersen commented
uncrustify, rebased, and merged.

Thanks for your contribution !

2023-06-05 11:40 UTC, closed without merging