Design dashboard for current metrics
pgmoneta/pgmoneta pull request #126
Opened 2023-06-09 14:14 UTC by linzs148

[design dashboard for current metrics and add user document for it](https://github.com/pgmoneta/pgmoneta/commit/6ebbe7ce1e8e868ce929bae4d3ed57ebf13886a3)

2023-06-12 15:14 UTC, jesperpedersen commented
@linzs148 Please, rebase, and squash your commits
@MariamFahmy98 PTAL

2023-06-13 07:54 UTC, linzs148 commented
> @linzs148 Please, rebase, and squash your commits

I have removed the merge commit

2023-06-13 07:57 UTC, linzs148 commented
> @linzs148 Please, rebase, and squash your commits @MariamFahmy98 PTAL

I have removed the merge commit to meke it clean.

2023-06-15 10:54 UTC, MariamFahmy98 commented
Thanks for the PR. It's good for me.

2023-06-15 10:57 UTC, jesperpedersen commented
I think we need an issue for this that can be referenced in the commit message.

And, I think we need some screenshots on the issue or in the discussion thread.

2023-06-29 14:05 UTC, jesperpedersen commented
@linzs148 Where are we on https://github.com/pgmoneta/pgmoneta/pull/126#issuecomment-1592827556 ?

2023-07-10 13:54 UTC, jesperpedersen commented
@linzs148 ping ?

2023-07-11 06:57 UTC, linzs148 commented
> @linzs148 ping ?

I have related this pull request with issue [#133] and put screenshots on issue and discussion.

2023-07-17 12:42 UTC, jesperpedersen commented
Could you get the feedback sorted this week, please ?

2023-07-17 12:56 UTC, linzs148 commented
> Could you get the feedback sorted this week, please ?

What does this feedback mean? Comments in this pullrequest or something else?

2023-07-17 12:58 UTC, jesperpedersen commented
https://github.com/pgmoneta/pgmoneta/issues/133#issuecomment-1630773387

2023-07-18 15:28 UTC, jesperpedersen requested changes

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +This tutorial will show you how to encapsulate prometheus standard API and use them to monitor state of pgmoneta with the help of grafana dashboard.
prometheus -> Prometheus
grafana -> Grafana

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +First of all, you should install prometheus in your pgmoneta server. For `Ubuntu 22.04`, you can just use `apt-get` command to install it.
prometheus -> Prometheus

Remove "For `Ubuntu 22.04`, you can just use `apt-get` command to install it."

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +After you successfully install prometheus, you should replace `prometheus.yml ` with content below (For `Ubuntu 22.04`, the whole path is `/etc/prometheus/prometheus.yml`) to configure how to query y
"installed"
"with the content below"

Remove "(For `Ubuntu 22.04`, the whole path is `/etc/prometheus/prometheus.yml`) to configure how to query your pgmoneta metrics"

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +Then the prometheus service will query your pgmoneta metrics every 15 seconds and package them as time-series data. You can query your pgmoneta metrics and watch their changes as time passed in prome
prometheus -> Prometheus

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +![](https://linzs-upload.oss-cn-shanghai.aliyuncs.com/img/prometheus2.jpg)
Needs to be added to the directory

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +![](https://linzs-upload.oss-cn-shanghai.aliyuncs.com/img/prometheus3.jpg)
Needs to be added to the directory

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +Although prometheus provides capacity of querying and monitoring metrics, we can not customize graph for each metric and place them together.
prometheus -> Prometheus
graph -> graphs

"and place them together" -> "and provide a unified view"

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +As a result, we use grafana to help us manage all graphs together. First of all, we should install grafana in the computer you need to monitor pgmoneta metrics. You can browse grafana web page with d
grafana -> Grafana

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +![](https://linzs-upload.oss-cn-shanghai.aliyuncs.com/img/grafana1.jpg)
Needs to be added to the directory

2023-07-18 15:28 UTC, jesperpedersen commented on doc/tutorial/10_grafana.md
> +Finally you can create dashboard by importing `conmtrib/grafana/dashboard.json` and monitor metrics about pgmoneta.
`conmtrib/` -> `contrib/`

2023-07-18 15:28 UTC, jesperpedersen commented
Add a link from the `GETTING_STARTED.md` to the tutorial

2023-07-19 09:48 UTC, jesperpedersen commented
@linzs148 Please, get this sorted quickly

2023-07-22 07:41 UTC, linzs148 commented
> @linzs148 Please, get this sorted quickly

@jesperpedersen I have changed the commit and the workflow needs to be approved.

2023-07-24 12:52 UTC, merged

2023-07-24 12:52 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

Please, continue discussing what the next steps are in your forum thread.