[#123] Receive and extract base backup archive (for server version < 15)
pgmoneta/pgmoneta pull request #130
Opened 2023-07-04 03:01 UTC by Jubilee101

Finally! This is our native implementation of receiving and extracting the basebackup and the mainfest postgres server sends us. It uses libarchive to do the tar file extraction. We also support tablespaces now, for convenience I had to add the oid feild to the tablespace struct. So that I can keep track of and update the symbolic link easily. Let me know if you find it not ok. 

This implementation only works for server with version < 15, which sends tar file for each tablespaces separately. For server whose version >= 15, everything is sent in one backup stream so it's slightly different. 

I also have hesitations on whether to extract some parts into functions or if I'm putting the functionality in the right file. Feel free to give suggestions.

The correctness has be manually verified. But I couldn't really put it to test until in the end I also implement the xlog streaming.

2023-07-04 14:04 UTC, jesperpedersen commented
Lets see if we can get >= 15 into this pull request as well

2023-07-04 19:05 UTC, Jubilee101 commented
> Lets see if we can get >= 15 into this pull request as well

Sure

2023-07-05 21:57 UTC, Jubilee101 commented
New changes have been submitted. I verified the correctness manually for both server version >= 15 and < 15. But nevertheless I wrote in a very fast pace so it still requires careful review.

2023-07-06 06:42 UTC, Jubilee101 commented
I found a memory leak in my code but I'm unable to locate it for now. Please wait a little until I find it and resolve this issue :(

2023-07-07 01:08 UTC, Jubilee101 commented
I just locate the bugs and I think it's ok to merge.

2023-07-10 16:33 UTC, jesperpedersen requested changes

2023-07-10 16:33 UTC, jesperpedersen commented on src/include/message.h
> +#include <tablespace.h>
sorting

2023-07-10 16:33 UTC, jesperpedersen commented on src/include/tablespace.h
> +   unsigned int oid; /**< [[maybe_unused]] The oid of the table space */
Document the rest, and align comments

2023-07-10 16:33 UTC, jesperpedersen commented on src/include/utils.h
> +pgmoneta_compare_string(const char* str1, const char* str2);
Can we do with `!strcmp()` ?

2023-07-10 16:33 UTC, jesperpedersen commented on src/libpgmoneta/archive.c
> +      char dst_file_path[256];
MAX_PATH_LENGTH

2023-07-10 16:33 UTC, jesperpedersen commented on src/libpgmoneta/message.c
> +      char file_path[256];
MAX_PATH_LENGTH

2023-07-10 16:33 UTC, jesperpedersen commented on src/libpgmoneta/message.c
> +   char file_path[256];
MAX_PATH_LENGTH

2023-07-10 16:33 UTC, jesperpedersen commented on src/libpgmoneta/message.c
> +   char file_path[256];
MAX_PATH_LENGTH

2023-07-10 16:33 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +pgmoneta_compare_string(const char* str1, const char* str2)
Yeah, just keep this function

2023-07-10 16:43 UTC, Jubilee101 commented on src/include/utils.h
> +pgmoneta_compare_string(const char* str1, const char* str2);
It's there to deal with null inputs.

2023-07-10 16:44 UTC, Jubilee101 commented on src/include/message.h
> + * This functionality is for server version < 15,
Oh that actually reminds me. I didn't check server version when it comes to manifest. I'm on it.

2023-07-10 16:46 UTC, Jubilee101 commented on src/libpgmoneta/utils.c
> +pgmoneta_compare_string(const char* str1, const char* str2)
Gotcha

2023-07-10 18:14 UTC, Jubilee101 commented
Changes submitted

2023-07-11 12:42 UTC, merged

2023-07-11 12:42 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !