[#123] Base backup functionality integration
pgmoneta/pgmoneta pull request #134
Opened 2023-07-11 20:11 UTC by Jubilee101

2023-07-11 20:14 UTC, Jubilee101 commented
Hmm, the ci check failed. I'm working on it.

2023-07-11 20:40 UTC, Jubilee101 commented
I found that postgres sometimes sends me copydata message with no actual payload (what the hell?). So I added some extra checking to prevent false alarm.

2023-07-12 12:14 UTC, jesperpedersen requested changes

2023-07-12 12:14 UTC, jesperpedersen commented on src/libpgmoneta/wf_backup.c
> +#include <security.h>
Sorting

2023-07-12 12:14 UTC, jesperpedersen commented on src/libpgmoneta/wf_backup.c
> +#include <string.h>
Sorting

2023-07-12 18:29 UTC, jesperpedersen requested changes

2023-07-12 18:29 UTC, jesperpedersen commented on src/libpgmoneta/wf_backup.c
> +#include <pgmoneta.h>
This one is always first

2023-07-12 18:32 UTC, Jubilee101 commented on src/libpgmoneta/wf_backup.c
> +#include <pgmoneta.h>
😆 So sorry about that. It's fixed now.

2023-07-12 18:34 UTC, merged

2023-07-12 18:34 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !