A new function to retrieve file's permissions
pgmoneta/pgmoneta pull request #189
Opened 2024-02-27 01:08 UTC by HazemRawi

Hi,
In utils.c the function named pgmoneta_copy_file()  always creates a new file with specified permissions

`   fd_to = open(to, O_WRONLY | O_CREAT | O_EXCL, 0664);`

0664 are the permissions in octal this is not correct so we have to make sure that the newly created file **to** inherits the same permissions of the parent file **from**

`    *permissions = from_stat.st_mode & (S_IRWXU | S_IRWXG | S_IRWXO);`
Here I only take care of permissions given to:
-owner (S_IRWXU)
-group (S_IRWXG)
-other (S_IRWXO)
that's why I bitmask the value of .st_mode

Errors related to **from** file can be handled in pgmoneta_copy_file() function but when to comes to stat failure I preferred to delegate the task of logging the error to the caller function because -till now- the newly created function is nested into pgmoneta_copy_file()

Waiting for your feedback!

2024-02-27 13:27 UTC, jesperpedersen requested changes

2024-02-27 13:27 UTC, jesperpedersen commented on src/include/utils.h
> +pgmoneta_get_permissions(char* from,int* permissions);
I don't think that we need it as a public function right now

2024-02-27 13:27 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +pgmoneta_get_permissions(char* from, int* permissions) {
static function instead

2024-02-27 13:27 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +    if (stat(from, &from_stat) == -1) {
You need to run uncrustify as well...

2024-02-27 13:27 UTC, jesperpedersen commented
You need to update the `AUTHORS` file as well.

Remember to squash your commits and then force push.

2024-02-27 13:28 UTC, jesperpedersen requested changes

2024-02-27 13:28 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +   if(pgmoneta_get_permissions(from,&permissions)==1)
You don't need the `== 1` here...

2024-02-27 17:12 UTC, HazemRawi commented
All requested changes updated but when I ran uncrustify there were some edited lines of pgmoneta.h.

2024-02-27 19:41 UTC, jesperpedersen requested changes

2024-02-27 19:41 UTC, jesperpedersen commented on src/include/pgmoneta.h
>  #define unlikely(x)  __builtin_expect (!!(x), 0)
You can leave these changes out

2024-02-27 19:41 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +pgmoneta_get_permissions(char* from, int* permissions)
You need a definition at the top of the file.

And, static functions doesn't have to start with `pgmoneta_` in their name

2024-02-27 23:00 UTC, HazemRawi commented
I have completed all requested changes ,waiting for your feedback!

2024-02-28 13:01 UTC, jesperpedersen requested changes

2024-02-28 13:01 UTC, jesperpedersen commented on src/libpgmoneta/utils.c
> +static int
Single line here, please.

Follow the style around your changes.

2024-02-28 13:02 UTC, jesperpedersen commented
Create an issue for this, and reference that issue number in your commit message.

See the Git commit log for examples

2024-02-29 16:23 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

2024-02-29 16:23 UTC, closed without merging