[#221] Add a label of minor version in backup.info
pgmoneta/pgmoneta pull request #223
Opened 2024-03-21 21:07 UTC by l32zhao

I added a **MINOR_VERSION** label to record the minor version of the Postgres server in "backup.info" generated after making a full backup.

2024-03-21 21:20 UTC, jesperpedersen commented
Only change what your patch is about... and use the same pull request

2024-03-22 02:02 UTC, l32zhao commented
> Only change what your patch is about... and use the same pull request

Sorry about that, some codes were changed by Uncrustify. I have fixed it.

2024-03-22 02:20 UTC, Jubilee101 commented
Seems that some code got in without formatting @jesperpedersen

2024-03-22 02:25 UTC, Jubilee101 commented
@l32zhao What is your uncrustify version? We are using 0.77. Otherwise some code got in without formatting

2024-03-22 02:47 UTC, l32zhao commented
> @l32zhao What is your uncrustify version? We are using 0.77. Otherwise some code got in without formatting

It's 0.76.0-2.fc38, I will try to upgrade it.

2024-03-22 03:53 UTC, l32zhao commented
@Jubilee101 I upgraded uncrustify to 0.77.1 (Fedora39), but the result is still as same as my last commit, except for some modified codes not in my patch (like workers.h, workers.c, and bzip2_compression.c). Could you help me to have a look?

<img width="1746" alt="image" src="https://github.com/pgmoneta/pgmoneta/assets/29018475/7ad0ffa0-c4d9-4f65-8e2a-3b897e73a804">

2024-03-22 03:57 UTC, Jubilee101 commented
Hi, that is ok. Could you revert the format changes that are not in your code? We'll submit a separate patch for formatting. Sorry for the trouble. Other than that, the code looks good to me~

2024-03-22 04:52 UTC, l32zhao commented
> Hi, that is ok. Could you revert the format changes that are not in your patch? We'll submit a separate patch for formatting. Sorry for the trouble. Other than that, the code looks good to me~

Thanks, man. The current commit doesn't involve any format change not for adding the minor_version label. Please feel free to review it and pull it~

2024-03-22 05:21 UTC, jesperpedersen requested changes

2024-03-22 05:21 UTC, jesperpedersen commented on src/libpgmoneta/wf_backup.c
> +   snprintf(minor_version, sizeof(version), "%d", config->servers[server].minor_version);
minor_version

2024-03-22 05:46 UTC, merged

2024-03-22 05:46 UTC, jesperpedersen commented
Merged.

Welcome to the community !

Thanks for your contribution !