Prometheus metric for backup version shows major and minor version
pgmoneta/pgmoneta pull request #240
Opened 2024-04-03 23:09 UTC by iuryr

This pull request implements a change to the prometheus metric `pgmoneta_backup_server_version` in order to show major and minor versions separately.

- `src/libpgmoneta/info.c` changes populates `backup->minor_version` with pertinent information
- `src/libpgmoneta/prometheus.c` changes adjusts the display of the metric in order to show aforementioned data

2024-04-04 10:30 UTC, jesperpedersen commented
You need to add your name to `AUTHORS`.

Then squash, rebase and force push

2024-04-04 23:55 UTC, iuryr commented
> You need to add your name to `AUTHORS`.
> 
> Then squash, rebase and force push

Done!

2024-04-05 10:28 UTC, jesperpedersen commented
`pgmoneta_backup_version` isn't documented on the main page, can you make sure that all metrics are ?

Do `git grep "#TYPE"` and make sure they are in the `home_page()` function.

Squash, rebase and force push.

Thanks !

2024-04-05 13:41 UTC, iuryr commented
@jesperpedersen The changes you asked in https://github.com/pgmoneta/pgmoneta/pull/240#issuecomment-2039444518 are implemented, please review to see if I let something slip by.

I edited https://github.com/pgmoneta/pgmoneta/pull/240#issue-2224099427 to include the changes in src/libpgmoneta/prometheus.c

Also, before the changes above, I synced my fork with pgmoneta repo and did a `git pull` so the commits of the main branch are now included in this PR. I don't know if this messes with some workflow somehow. If it does, please advise of how I can fix it.

Thank you!

2024-04-05 13:53 UTC, iuryr commented
Yeah, just had to rebase and drop the commits that got included because of the pull. Only one commit in this PR now. Phew :sweat_smile:

2024-04-05 13:55 UTC, iuryr commented
aaaand I just realized that you asked me to check that all other metrics are documented in `home_page` function. Sorry. Will check and update the PR later!

2024-04-05 15:34 UTC, jesperpedersen requested changes

2024-04-05 15:34 UTC, jesperpedersen commented on src/libpgmoneta/prometheus.c
> +   data = pgmoneta_append(data, "        <td>The backup postgresql major version</td>\n");
Its `PostgreSQL`

2024-04-05 15:34 UTC, jesperpedersen commented on src/libpgmoneta/prometheus.c
> +   data = pgmoneta_append(data, "        <td>The backup postgresql minor version</td>\n");
Same

2024-04-05 15:35 UTC, jesperpedersen commented
There is still something wrong with your rebase...

https://www.git-tower.com/learn/git/faq/git-squash
https://github.com/progit/progit2/releases/tag/2.1.425

2024-04-06 17:07 UTC, jesperpedersen commented
You can use the same PR, just force push

https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md#basic-git-guide

2024-04-06 17:18 UTC, iuryr commented
I discarded my commit only on my remote fork of pgmoneta and Github automatically closed the PR (I did not know it would do that). I'm working on the changes now and will reuse this PR, as avised. Thank you!

2024-04-06 19:02 UTC, iuryr commented
Reopening PR with (hopefully) no rebase problems and with all prometheus metrics documented in `home_page()`.

2024-04-06 23:08 UTC, merged

2024-04-06 23:09 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !

2024-04-17 19:09 UTC, iuryr commented
@jesperpedersen I noticed a typo in `prometheus.c`. A  `td` tag that is not properly closed in line 294 in the file version of this commit. Should I reopen the PR and fix it?

2024-04-17 19:42 UTC, jesperpedersen commented
Yes

2024-04-17 19:43 UTC, jesperpedersen commented
You can use https://validator.w3.org/

2024-04-18 13:05 UTC, iuryr commented
Jesper, 

It seems that I cannot reuse this PR to submit the fix, since it has already been merged. I will open another PR and reference this one, if that's ok with you. Please let me know. Thanks

2024-04-18 15:51 UTC, jesperpedersen commented
Yeah, that is ok