[#265] initial manual
pgmoneta/pgmoneta pull request #273
Opened 2024-04-18 19:09 UTC by GuChad369

- Add a new initial `/manual` directory.
- Modify the `CMake` file to enable the use of `pandoc` and `LaTeX` for generating `.html` and `.pdf` files from `Markdown`.
- Update the Git `.workflows`.

2024-04-19 08:56 UTC, jesperpedersen commented
```
-- System is Linux
-- pandoc found
CMake Error at cmake/FindPdflatex.cmake:14 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  CMakeLists.txt:85 (find_package)
```

```
which pdflatex
/usr/bin/pdflatex
```

```
pdflatex --version
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

2024-04-19 08:58 UTC, jesperpedersen commented
You need to update `README.md` and `pgmoneta.spec` with the files

2024-04-19 09:04 UTC, jesperpedersen commented
Make sure that you verify on Fedora / RHEL 8 / RHEL 9

2024-04-19 13:00 UTC, GuChad369 commented
Could you provide some guidance on the pgmoneta.spec file? I am not familiar with it.

2024-04-19 13:15 UTC, jesperpedersen commented
You need to make

* A directory (see around https://github.com/pgmoneta/pgmoneta/blob/main/pgmoneta.spec#L33)
* Copy the .pdf and .html in (see around https://github.com/pgmoneta/pgmoneta/blob/main/pgmoneta.spec#L71)
* Define them (see around https://github.com/pgmoneta/pgmoneta/blob/main/pgmoneta.spec#L122)

Take a look at https://github.com/pgmoneta/pgmoneta/blob/main/doc/RPM.md

2024-04-19 20:20 UTC, GuChad369 commented
I've updated the README and `pgmoneta.spec` files; the RPM was successfully tested on Fedora.

2024-04-20 02:33 UTC, jesperpedersen commented
cmake is ok, but

```
[ 98%] Generating HTML documentation
[100%] Generating PDF documentation
Error producing PDF.
! LaTeX Error: File `footnote.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.86 \makesavenoteenv

make[2]: *** [src/CMakeFiles/all_docs.dir/build.make:100: doc/pgmoneta-manual.en.pdf] Error 43
make[1]: *** [CMakeFiles/Makefile2:254: src/CMakeFiles/all_docs.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

2024-04-20 02:35 UTC, jesperpedersen commented
```
dnf install -y texlive-latex-extra
Last metadata expiration check: 0:20:02 ago on Fri 19 Apr 2024 10:14:28 PM EDT.
No match for argument: texlive-latex-extra
Error: Unable to find a match: texlive-latex-extra
```

```
rpm -qa | grep texlive-scheme-basic
texlive-scheme-basic-svn54191-69.fc39.noarch
```

2024-04-20 02:36 UTC, jesperpedersen commented
Its Fedora 39

2024-04-20 12:20 UTC, GuChad369 commented
We're facing a problem with `pdflatex` as it doesn't have a specific library. To use `pdflatex`, we must download additional libraries like `TeX Live`, but each system offers different libraries for LaTeX. Our project also requires the `footnote.sty` package and different libraries may not offer the same method to verify its availability. Should we focus on solving this issue only for the Fedora system?

2024-04-20 12:35 UTC, jesperpedersen commented
The `README.md` should cover Fedora, the rest should be documented in https://github.com/pgmoneta/pgmoneta/blob/main/doc/DISTRIBUTIONS.md

2024-04-20 12:40 UTC, jesperpedersen commented
The key package for Fedora is `texlive-mdwtools`

2024-04-20 13:45 UTC, GuChad369 commented
I used two other ways to install the related libraries. `texlive-mdwtools` does not include `pdflatex`.

2024-04-20 14:06 UTC, jesperpedersen commented
Yeah, I know - but we need it for the style

2024-04-20 16:20 UTC, GuChad369 commented
Okay, let’s try it.

2024-04-23 00:09 UTC, GuChad369 commented
- I've restructured the manual without splitting it into two separate documents, as I noticed duplicate content for both users and developers. Separating them would result in excessive repetition. 
- We can enhance the content further at a later stage.

2024-04-23 19:49 UTC, jesperpedersen commented
There are some formatting issues, especially in "Configuration" chapter.

And, we don't need "Architecture" under introduction that is an advanced developer chapter - so close to last.

Take a step back, and think about what a new user of pgmoneta would like to know about going from install to their first backup

2024-04-23 19:59 UTC, jesperpedersen requested changes

2024-04-23 19:59 UTC, jesperpedersen commented on doc/manual/00-head.en.md
> +% pgmoneta Manual
We don't need "Manual"

2024-04-23 19:59 UTC, jesperpedersen commented on doc/manual/00-head.en.md
> +% PostgreSQL
Remove

2024-04-23 19:59 UTC, jesperpedersen commented on doc/manual/00-head.en.md
> +% April 18, 2024 (0.10.1)
Remove

2024-04-23 19:59 UTC, jesperpedersen commented on doc/manual/01-introduction.en.md
> +
We need something something about RPO and RTO in the Introduction, but we could take that later

2024-04-24 19:49 UTC, GuChad369 commented
I made some formatting changes. While `pandoc`'s default compilation can't handle all `Markdown` formatting, if we want a perfect HTML format, we must add a `CSS` file when `pandoc` compiles the HTML.

2024-04-24 20:29 UTC, jesperpedersen commented
We can likely find ways to improve the layout, colors, ...

2024-04-24 20:29 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

2024-04-24 20:29 UTC, closed without merging