[#276]Support WAL shipping to ssh storage engine
pgmoneta/pgmoneta pull request #277
Opened 2024-04-21 19:40 UTC by HazemRawi

2024-04-21 23:07 UTC, Hazem-404 commented
> 

Very Good Code Hazem !

2024-04-22 12:31 UTC, jesperpedersen requested changes

2024-04-22 12:31 UTC, jesperpedersen commented on src/include/storage.h
> +sftp_file
Use an out parameter instead, and `int` as the return type with the status of the operation

2024-04-22 12:31 UTC, jesperpedersen commented on src/include/utils.h
> +mode_t
Same here

2024-04-22 12:31 UTC, jesperpedersen commented
There are some formatting changes - use `Uncrustify_d-0.77.1_f`

2024-04-22 12:32 UTC, jesperpedersen commented
Generally, I think this is going in the right direction... but I need to take a closer look

2024-04-23 12:31 UTC, GuChad369 commented
When GitHub runs the environment for macOS on this PR, it uses `/opt` as the global directory, whereas normally it should be `/usr`, which would already have the `ssh` library installed. I'm not sure why this change occurred. However, you can modify the `.github/workflows/ci.yml` file to install the library, or manually locate the library to ensure it works on macOS.

2024-04-23 21:48 UTC, HazemRawi commented
@GuChad369 Thanks for your help! 
Jesper handled this problem

2024-04-23 22:14 UTC, HazemRawi commented
I tested both workflows:

   -When the WAL segment file already exists.
   -When the WAL segment file needs to be created.

Everything works fine except that `sftp_wal_prepare()` takes about 12 minutes to execute. I suspect this delay might be due to the server(E2 server from Google cloud).
Do you have any ideas on how to improve this?

2024-04-24 09:01 UTC, jesperpedersen commented
Did you test it with a SSH server ? Or on your network ?

2024-04-24 09:24 UTC, HazemRawi commented
> Did you test it with a SSH server ? Or on your network ?

I test it using SSH server as described on `ssh.md`

>I suspect this delay might be due to the server

I mean the server doesn't come with a high system specification, As most of the time taken by `sftp_write() `.

2024-04-24 12:21 UTC, jesperpedersen commented
Ok, understood

2024-04-24 20:10 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

2024-04-24 20:10 UTC, closed without merging