[#311] Use stdint.h and stdbool.h for communication protocol
pgmoneta/pgmoneta pull request #329
Opened 2024-06-30 07:35 UTC by shikharish

2024-06-30 13:17 UTC, jesperpedersen commented
Can you reenable the MacOS build in https://github.com/pgmoneta/pgmoneta/blob/main/.github/workflows/ci.yml and see how it goes ?

2024-06-30 13:31 UTC, jesperpedersen requested changes

2024-06-30 13:31 UTC, jesperpedersen commented on src/include/info.h
> +   uint64_t backup_size;                                     /**< The backup size */
Align comments

2024-06-30 13:31 UTC, jesperpedersen commented on src/libpgmoneta/json.c
> +#include <stdint.h>
Sorting

2024-06-30 13:31 UTC, jesperpedersen commented on src/libpgmoneta/json.c
> +   struct json_value* val = pgmoneta_json_get_value(item, key);
Can you move `struct json_value* val = NULL;` to the beginning of the function ?

2024-06-30 13:31 UTC, jesperpedersen commented on src/libpgmoneta/management.c
> +      // number_of_backups=1;
Remove

2024-06-30 13:31 UTC, jesperpedersen commented on src/libpgmoneta/management.c
> +         pgmoneta_log_info("n_backups %d", number_of_backups);
Remove

2024-06-30 20:24 UTC, jesperpedersen commented
There is something wrong...

Look at the output from the `info` command; `-F json` works, but `-F text` doesn't

2024-07-01 12:45 UTC, shikharish commented
@jesperpedersen Should work now.

2024-07-01 13:12 UTC, merged