[#377] Management: Support encryption
pgmoneta/pgmoneta pull request #406
Opened 2024-10-17 20:27 UTC by GuChad369

- Expose a new variable, `encryption`, to support encryption and decryption of the wire protocol.
- Create a new function, `pgmoneta_encrypt_decrypt_buffer`, to support three modes for encrypting and decrypting buffers.

2024-10-18 01:55 UTC, jesperpedersen requested changes

2024-10-18 01:55 UTC, jesperpedersen commented on src/cli.c
> +            if (!strncmp(optarg, "aes256", MISC_LENGTH))
`aes`

2024-10-18 01:55 UTC, jesperpedersen commented
There is `doc/manual/user-10-cli.md`

2024-10-18 02:02 UTC, jesperpedersen commented on src/cli.c
> +            if (!strncmp(optarg, "aes256", MISC_LENGTH))
... including docs ...

2024-10-18 07:32 UTC, jesperpedersen commented on src/cli.c
> +            if (!strncmp(optarg, "aes256", MISC_LENGTH))
I meant, we support both - `aes` is just an alias for `aes256`

2024-10-18 07:35 UTC, jesperpedersen commented on src/libpgmoneta/aes.c
> +      pgmoneta_log_fatal("EVP_CIPHER_CTX_new: Failed to create context");
`_error`

2024-10-18 20:49 UTC, GuChad369 commented
updated

2024-10-18 23:07 UTC, jesperpedersen commented
Rebase, please

2024-10-18 23:28 UTC, jesperpedersen commented
It should be both `aes` and `aes256` as options.

It crashes,

```
    #1 0x7ff96a6f1d19 in pgmoneta_json_parse_string src/libpgmoneta/json.c:534:23
    #2 0x7ff96a7064d4 in pgmoneta_management_read_json src/libpgmoneta/management.c:1009:8
```

with

```
pgmoneta-cli -E aes expunge primary 20241012091219
```

Remember to test with `-C zstd` too

2024-10-18 23:46 UTC, GuChad369 commented
> It crashes,
> 
> ```
>     #1 0x7ff96a6f1d19 in pgmoneta_json_parse_string src/libpgmoneta/json.c:534:23
>     #2 0x7ff96a7064d4 in pgmoneta_management_read_json src/libpgmoneta/management.c:1009:8
> ```

The crash is not related to these new functions. I tested them, and the functionality of the new feature works well. 

As for the memory leak, it's due to the function `pgmoneta_json_parse_string`, not an issue with my logic.

2024-10-18 23:49 UTC, GuChad369 commented
After adding log traces, both sides are printing the correct information, confirming that the crash is not related to the newly added logic.

```consle
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -E aes expunge primary 20241013082700
Original string {"Header":{"ClientVersion":"0.15.0","Command":13,"Output":0,"Timestamp":"20241018194214"},"Request":{"Backup":"20241013082700","Server":"primary"}}
Compressed size 147
Encrypt size 160
Encode string JUYMVx9hqnpVM85iRm1EAytVR6QuKAvDytFtdK9GExRVtU95Q5mIcTm2IXOgz4onx+2TlAubCsFvoPv1ygyBXp3koH9uxeCBqoOThAH3PjW8t9Rza/n5OHpiO6Y4I2edN84+GuvzjeGv/dNxlw1maub2LYnSGlQrON3JFF8U5cnbbXUBOiJJN1nz1VpWRdLtJsQ63RX6HMD8qsdJjg5V5w==
Reading Original string JUYMVx9hqnpVM85iRm1EAytVR6QuKAvDytFtdK9GExRVtU95Q5mIcTm2IXOgz4onx+2TlAubCsFvoPv1ygyBXp3koH9uxeCBqoOThAH3PjUAaNxOIA9ZUsm9Wy7O4fLX/hmjE30GzOYOlqDMm7ZfkQmTdE2rOZgQAj3nbX2LYfVbxXT02u4HtHwVf/0ICtLF5Uoe/rJUrHGqsQLiq2PlW+R7o2e1c93Mkis7lcTO9Fx1CRPvt7+8zODyFG2gK9Gv7EmUDIF8A/k4iBwuCFa8wGb+qMBRlTCRvdfBRPQJvi/BpYaoDkG32KEQCIy5zhXblPG+VNdCjt87wXoGVmZGFdn2mZJMFwTZ0rkBP1JL+U0jtbLJHspZYbW+wYBDeKnkKZVa99vZ6ZvwY/OjF+ei0+Kcvcja/9DJwPwG9lTkbmjMiafHoKek3iQGl4n45qULXR10fPC6/vOgWaoGXt5DJUsgm8afC4q+4aXwZKM9Ss1+kYHhcqGg1pzbrKC5lFUTk02UnWfolcWNi7na59Cf06VdsrOiilXcOik8fzD6pmBPCfMiduG8X01Ru1AOUFuRNpUrr7p4ivlTW6pSHo+Vzjbdkekx5SfvTF3JLc08c1gPtL9NWm77gF67wbq5EyoS
Reading decode size 480
Reading decrypt size 471
Reading decompress string {"Header":{"ClientVersion":"0.15.0","Command":13,"Output":0,"Timestamp":"20241018194214"},"Outcome":{"Status":true,"Time":"00:00:00"},"Request":{"Backup":"20241013082700","Server":"primary"},"Response":{"Backup":"20241013082700","Comments":"/home/postgres/pgsql/pg_replslot/repl/state, /home/postgres/pgsql/pg_replslot/log.txt, /home/postgres/pgsql/pg_replslot/tmp/da,"Keep":false,"MajorVersion":15,"MinorVersion":1,"Server":"primary","ServerVersion":"0.15.0","Valid":1}}�6�+��x��S[�R���a�
pgmoneta-cli: No connection to pgmoneta on /tmp/
```

```consle
[pgmoneta@fedora-linux-38 ~]$ pgmoneta -c pgmoneta.conf -u pgmoneta_users.conf
2024-10-18 19:42:08 INFO  main.c:661 Started on localhost
Reading Original string JUYMVx9hqnpVM85iRm1EAytVR6QuKAvDytFtdK9GExRVtU95Q5mIcTm2IXOgz4onx+2TlAubCsFvoPv1ygyBXp3koH9uxeCBqoOThAH3PjW8t9Rza/n5OHpiO6Y4I2edN84+GuvzjeGv/dNxlw1maub2LYnSGlQrON3JFF8U5cnbbXUBOiJJN1nz1VpWRdLtJsQ63RX6HMD8qsdJjg5V5w==
Reading decode size 160
Reading decrypt size 147
Reading decompress string {"Header":{"ClientVersion":"0.15.0","Command":13,"Output":0,"Timestamp":"20241018194214"},"Request":{"Backup":"20241013082700","Server":"primary"}}
Original string {"Header":{"ClientVersion":"0.15.0","Command":13,"Output":0,"Timestamp":"20241018194214"},"Outcome":{"Status":true,"Time":"00:00:00"},"Request":{"Backup":"20241013082700","Server":"primary"},"Response":{"Backup":"20241013082700","Comments":"/home/postgres/pgsql/pg_replslot/repl/state, /home/postgres/pgsql/pg_replslot/log.txt, /home/postgres/pgsql/pg_replslot/tmp/da,"Keep":false,"MajorVersion":15,"MinorVersion":1,"Server":"primary","ServerVersion":"0.15.0","Valid":1}}
Compressed size 471
Encrypt size 480
Encode string JUYMVx9hqnpVM85iRm1EAytVR6QuKAvDytFtdK9GExRVtU95Q5mIcTm2IXOgz4onx+2TlAubCsFvoPv1ygyBXp3koH9uxeCBqoOThAH3PjUAaNxOIA9ZUsm9Wy7O4fLX/hmjE30GzOYOlqDMm7ZfkQmTdE2rOZgQAj3nbX2LYfVbxXT02u4HtHwVf/0ICtLF5Uoe/rJUrHGqsQLiq2PlW+R7o2e1c93Mkis7lcTO9Fx1CRPvt7+8zODyFG2gK9Gv7EmUDIF8A/k4iBwuCFa8wGb+qMBRlTCRvdfBRPQJvi/BpYaoDkG32KEQCIy5zhXblPG+VNdCjt87wXoGVmZGFdn2mZJMFwTZ0rkBP1JL+U0jtbLJHspZYbW+wYBDeKnkKZVa99vZ6ZvwY/OjF+ei0+Kcvcja/9DJwPwG9lTkbmjMiafHoKek3iQGl4n45qULXR10fPC6/vOgWaoGXt5DJUsgm8afC4q+4aXwZKM9Ss1+kYHhcqGg1pzbrKC5lFUTk02UnWfolcWNi7na59Cf06VdsrOiilXcOik8fzD6pmBPCfMiduG8X01Ru1AOUFuRNpUrr7p4ivlTW6pSHo+Vzjbdkekx5SfvTF3JLc08c1gPtL9NWm77gF67wbq5EyoS
2024-10-18 19:42:14 INFO  keep.c:180 Expunge: primary/20241013082700 (Elapsed: 00:00:00)
```

2024-10-19 00:40 UTC, jesperpedersen commented
Did you find the root cause ?

2024-10-19 00:52 UTC, GuChad369 commented
Not yet. It seems to be related to other functions that I'm not familiar with. I'm not entirely sure what each function does, but based on the log, everything points to the file `art.c`.

```console
==3054104== 128 bytes in 1 blocks are possibly lost in loss record 82 of 93
==3054104==    at 0x48C0860: malloc (vg_replace_malloc.c:442)
==3054104==    by 0x53E6623: create_art_node (art.c:428)
==3054104==    by 0x53E6DBF: art_node_insert (art.c:640)
==3054104==    by 0x53E637B: pgmoneta_art_insert (art.c:354)
==3054104==    by 0x53FBFD3: pgmoneta_json_put (json.c:364)
==3054104==    by 0x540506F: create_outcome_success (management.c:1641)
==3054104==    by 0x5403583: pgmoneta_management_response_ok (management.c:788)
==3054104==    by 0x53FE73F: keep (keep.c:162)
==3054104==    by 0x53FE1F3: pgmoneta_expunge_backup (keep.c:52)
==3054104==    by 0x11BD2F: accept_mgt_cb (main.c:1266)
==3054104==    by 0x4AE20CB: ev_invoke_pending (ev.c:3770)
==3054104==    by 0x4AE5C43: UnknownInlinedFun (ev.c:4190)
==3054104==    by 0x4AE5C43: ev_run (ev.c:4021)
==3054104== 
==3054104== 128 bytes in 4 blocks are possibly lost in loss record 83 of 93
==3054104==    at 0x48C0860: malloc (vg_replace_malloc.c:442)
==3054104==    by 0x542F75F: pgmoneta_value_create (value.c:69)
==3054104==    by 0x53E657F: create_art_leaf (art.c:414)
==3054104==    by 0x53E6D17: art_node_insert (art.c:618)
==3054104==    by 0x53E637B: pgmoneta_art_insert (art.c:354)
==3054104==    by 0x53FBFD3: pgmoneta_json_put (json.c:364)
==3054104==    by 0x53FCC87: json_add (json.c:717)
==3054104==    by 0x53FCE53: fill_value (json.c:753)
==3054104==    by 0x53FC9BF: parse_string (json.c:647)
==3054104==    by 0x53FD09F: fill_value (json.c:796)
==3054104==    by 0x53FC9BF: parse_string (json.c:647)
==3054104==    by 0x53FC553: pgmoneta_json_parse_string (json.c:539)

```

2024-10-19 01:15 UTC, jesperpedersen commented
Start from `main.c` and work your way down

2024-10-19 01:16 UTC, jesperpedersen commented
Is it `pyl` ?

2024-10-19 01:26 UTC, GuChad369 commented
> Start from main.c and work your way down

I’ll try it, but this issue is unrelated to the current PR. If you test other CLI commands with the `-C` and `-E` options, you’ll see that the functionality in this PR works as expected.

> Is it `pyl` ?

what does this meaning?

2024-10-19 01:42 UTC, jesperpedersen commented
If I run this pull request without `-E`, I get no errors - so we have to track this down.

So, we have to figure out where the error is coming, first candidate is https://github.com/pgmoneta/pgmoneta/blob/main/src/main.c#L1262

2024-10-19 10:06 UTC, jesperpedersen commented
```
    #0 0x55e5700008e3 in malloc (build/src/pgmoneta+0xd28e3) (BuildId: d6aaab731c20881703a6274ce3b0c21eb96baedf)
->  #1 0x7ff96a69b97b in pgmoneta_encrypt_decrypt_buffer src/libpgmoneta/aes.c:898:34
    #2 0x7ff96a7060e8 in pgmoneta_management_read_json src/libpgmoneta/management.c:916:17
    #3 0x55e57004b060 in accept_mgt_cb src/main.c:828:8
```

Are you using a `Debug` build with clang ?

2024-10-19 12:02 UTC, GuChad369 commented
Yes, I'm using a Debug build with Clang. 

Right now, I'm still trying to understand the `expunge` command. I consistently encounter the following error, even when using it without the `-E` option:

```console
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli expunge primary 20241013082700
pgmoneta-cli: No connection to pgmoneta on /tmp/
```

However, when I check running processes, I see that `pgmoneta` is active:

```console
[root@fedora-linux-38 build]# ps aux | grep pgmoneta
pgmoneta 3060725  0.3  0.2  58000  5260 pts/2    S    00:28   1:44 pgmoneta: wal/primary
pgmoneta 3122712  0.3  2.1  57676 42624 pts/2    S+   07:48   0:00 pgmoneta: main
pgmoneta 3122714  0.5  0.2  58000  5260 pts/2    S+   07:48   0:00 pgmoneta: wal/primary
```

I'm still investigating why the connection to `pgmoneta` isn't being established despite it running in the background.

2024-10-19 12:12 UTC, jesperpedersen commented
It should be the same for all commands, so see if `status` works first, and then work from there

2024-10-19 12:21 UTC, GuChad369 commented
The strange issue is that they work perfectly when I use other commands. 

I've tested them several times, so I submitted this PR. I've also checked for memory leaks, and there's no leak associated with the logic in this PR.

```console
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -c pgmoneta.conf -F json -C gz -E aes status
{
  "Header": {
    "ClientVersion": "0.15.0",
    "Command": "status",
    "Output": "json",
    "Timestamp": "20241019081832"
  },
  "Outcome": {
    "Status": true,
    "Time": "00:00:00"
  },
  "Request": {},
  "Response": {
    "FreeSpace": "824.25MB",
    "NumberOfServers": 1,
    "Offline": false,
    "ServerVersion": "0.15.0",
    "Servers": [
      {
        "HotStandbySize": 0,
        "NumberOfBackups": 3,
        "RetentionDays": 7,
        "RetentionMonths": "Unspecified",
        "RetentionWeeks": "Unspecified",
        "RetentionYears": "Unspecified",
        "Server": "primary",
        "ServerSize": "34.52MB",
        "Workers": 0
      }
    ],
    "TotalSpace": "976.95MB",
    "UsedSpace": "34.52MB",
    "Workers": 0
  }
}
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -c pgmoneta.conf -C gz -E aes status
Header: 
  ClientVersion: 0.15.0
  Command: status
  Output: text
  Timestamp: 20241019081844
Outcome: 
  Status: true
  Time: 00:00:00
Request: 

Response: 
  FreeSpace: 824.25MB
  NumberOfServers: 1
  Offline: false
  ServerVersion: 0.15.0
  Servers: 
    - HotStandbySize: 0
      NumberOfBackups: 3
      RetentionDays: 7
      RetentionMonths: Unspecified
      RetentionWeeks: Unspecified
      RetentionYears: Unspecified
      Server: primary
      ServerSize: 34.52MB
      Workers: 0
  TotalSpace: 976.95MB
  UsedSpace: 34.52MB
  Workers: 0
```

```console
[pgmoneta@fedora-linux-38 ~]$ pgmoneta-cli -c pgmoneta.conf -E aes -C gz backup primary
Header: 
  ClientVersion: 0.15.0
  Command: backup
  Output: text
  Timestamp: 20241019081522
Outcome: 
  Status: true
  Time: 00:00:00
Request: 
  Server: primary
Response: 
  Backup: 20241019081522
  BackupSize: 5.00MB
  Compression: zstd
  Encryption: aes-128-ctr
  MajorVersion: 15
  MinorVersion: 1
  RestoreSize: 46.54MB
  Server: primary
  ServerVersion: 0.15.0
  Valid: yes
```

2024-10-19 12:27 UTC, jesperpedersen commented
I'm still getting 

```
    #0 0x55bd822e78e3 in malloc (build/src/pgmoneta+0xd28e3) (BuildId: d6aaab731c20881703a6274ce3b0c21eb96baedf)
    #1 0x7ff71909b97b in pgmoneta_encrypt_decrypt_buffer src/libpgmoneta/aes.c:898:34
    #2 0x7ff7191060e8 in pgmoneta_management_read_json src/libpgmoneta/management.c:916:17
```

from `status`

2024-10-19 12:29 UTC, jesperpedersen commented
You can try valgrind too

2024-10-19 12:31 UTC, jesperpedersen commented
`-C` on its own works

2024-10-19 12:54 UTC, GuChad369 commented
I still can’t find the memory leak in `pgmoneta_encrypt_decrypt_buffer`. Could you help me take a look at how we’re using it? After we use this function in `pgmoneta_management_read_json`, we replace it with `transfer_buffer`, and later we call `free(transfer_buffer)`. I don’t see any potential for a memory leak. I’m not sure why you’re encountering this issue.

2024-10-19 13:35 UTC, jesperpedersen commented
You are testing this like,

```
pgmoneta-cli -c pgmoneta.conf -E aes status
```

right ?

Because,

```
pgmoneta-cli -c pgmoneta.conf -C zstd -E aes status
```

works - so is encryption even active ?

2024-10-19 17:18 UTC, jesperpedersen commented
[logging.txt](https://github.com/user-attachments/files/17446701/logging.txt)

Doesn't seem like the string is `\0` terminated before parsed

2024-10-19 17:50 UTC, GuChad369 commented
> Doesn't seem like the string is `\0` terminated before parsed

If you add the following lines after `s = pgmoneta_json_to_string(json, FORMAT_JSON_COMPACT, NULL, 0);` in the `pgmoneta_management_write_json` function, you'll notice that when we first retrieve `s`, it is not properly terminated with `\0`:

```c
   size_t max_len = strlen(s);
   for (size_t i = 0; i < max_len; i++)
   {
      if (s[i] == '\0')
      {
         break;
      }
      if (i == max_len - 1)
      {
         pgmoneta_log_error("not terminated correctly");
         s[i] = '\0';
      }
   }
```

This code will help identify if the string is missing a null terminator.

2024-10-19 17:51 UTC, GuChad369 commented
The `pgmoneta_json_to_string` function does not properly handle the resulting string.

2024-10-19 17:54 UTC, GuChad369 commented
And if we forcibly correct it by adding a `\0`, the subsequent processes will fail, and the server will display the following error:

```console
2024-10-19 13:52:31 ERROR main.c:831 Management: Bad payload (1)
```

2024-10-19 18:19 UTC, GuChad369 commented
```c
   size_t max_len = strlen(s);
   if (s[max_len] != '\0')
   {
      pgmoneta_log_error("Reading not terminated correctly");
      s[max_len] = '\0';
   }
```
I tested it again using this approach to confirm if the string is not terminated properly, but so far, I haven't found any issues.

2024-10-19 21:46 UTC, Jubilee101 commented
> Doesn't seem like the string is \0 terminated before parsed

Jesper is right, the string is not \0 terminated. My guess is for decrytion alone it doesn't append trailing `\0`, but for decompression it does. That's why it works when `-C` is configured.

>    size_t max_len = strlen(s);
   if (s[max_len] != '\0')
   {
      pgmoneta_log_error("Reading not terminated correctly");
      s[max_len] = '\0';
   }

This won't work. You see `strlen` works by counting until `\0`. It won't work when the string is not terminated in the first place. @GuChad369

2024-10-19 22:05 UTC, Jubilee101 commented
Of course in gcc it often works, since the surrounding bytes of the string are very much likely to be 0 anyway. But with debug mode in clang the malloced memory is wrapped around protecting bytes (the red zone), that's why you are getting the error.

2024-10-20 13:54 UTC, GuChad369 commented
Thank you for explaining. It was my mistake. I updated the code and used the following command to build it:

```console
sudo cmake -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local ..
```

Now, I believe there are no errors anymore.

Please check if the current version is correct, and let me know if there are any other issues.

2024-10-20 16:04 UTC, jesperpedersen requested changes

2024-10-20 16:04 UTC, jesperpedersen commented on src/libpgmoneta/management.c
> +      printf("writing not terminated correctly\n");
Remove

2024-10-20 16:04 UTC, jesperpedersen commented on src/libpgmoneta/management.c
> +      s[max_len] = '\0'; // Manually null-terminate if needed
You should `append_char()`, right ?

2024-10-20 16:22 UTC, GuChad369 commented
rebase and update

2024-10-20 19:30 UTC, jesperpedersen commented
Rebase again, please

2024-10-20 20:05 UTC, merged

2024-10-20 20:05 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !