Adding a local storage workflow
pgmoneta/pgmoneta pull request #69
Opened 2022-06-26 15:08 UTC by MariamFahmy98

Adding a workflow node for the local storage engine.

2022-06-27 15:09 UTC, jesperpedersen requested changes

2022-06-27 15:09 UTC, jesperpedersen commented on doc/CONFIGURATION.md
> +| storage_engine | local | String | No | The storage engine type (local, ssh, s3) |
Remove ssh and s3 for now

2022-06-27 15:09 UTC, jesperpedersen commented on doc/GETTING_STARTED.md
> +storage_engine = local
Add this to the tutorials as well

2022-06-27 15:09 UTC, jesperpedersen commented on src/include/pgmoneta.h
> +#define STORAGE_ENGINE_SSH   1
Remove for now

2022-06-27 15:09 UTC, jesperpedersen commented on src/include/pgmoneta.h
> +#define STORAGE_ENGINE_S3    2
Remove for now

2022-06-27 15:09 UTC, jesperpedersen commented on src/libpgmoneta/configuration.c
> +   if (!strcasecmp(str, "ssh"))
Remove for now

2022-06-27 15:09 UTC, jesperpedersen commented on src/libpgmoneta/configuration.c
> +   if (!strcasecmp(str, "s3"))
Remove for now

2022-06-27 15:09 UTC, jesperpedersen commented on src/libpgmoneta/workflow.c
> +#include <stdio.h>
Is this necessary ?

2022-06-27 17:31 UTC, MariamFahmy98 commented on src/libpgmoneta/workflow.c
> +#include <stdio.h>
No, I removed it.

2022-06-28 11:55 UTC, merged

2022-06-28 11:57 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !