Adding a restore workflow
pgmoneta/pgmoneta pull request #73
Opened 2022-07-05 15:07 UTC by MariamFahmy98

2022-07-06 16:09 UTC, jesperpedersen requested changes

2022-07-06 16:09 UTC, jesperpedersen commented on src/include/node.h
> +int pgmoneta_destroy_node(struct node* in);
`pgmoneta_free_nodes(`

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/backup.c
> +   struct node** o_nodes = NULL;
struct node* o_nodes = NULL;

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/backup.c
> +      if (current->setup(server, &date[0], i_nodes, o_nodes))
`&o_nodes`

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/backup.c
> +      if (current->execute(server, &date[0], i_nodes, o_nodes))
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/backup.c
> +      if (current->teardown(server, &date[0], i_nodes, o_nodes))
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +
`node->next = NULL;`

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +         break;
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +         break;
Ditto

2022-07-06 16:09 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +   return *(bool*)current->data;
Lets return false here...

2022-07-06 16:09 UTC, jesperpedersen commented
Review - part 1...

2022-07-06 18:38 UTC, jesperpedersen requested changes

2022-07-06 18:38 UTC, jesperpedersen commented on src/libpgmoneta/wf_gzip.c
> +#include "node.h"
```
#include "node.h" --> #include <node.h>
```

2022-07-06 18:40 UTC, jesperpedersen requested changes

2022-07-06 18:40 UTC, jesperpedersen commented on src/libpgmoneta/node.c
> +         free(current);
You will need to free `data` and `tag` as well

2022-07-06 19:35 UTC, MariamFahmy98 commented
> Review - part 1...

Do you mean the storage engine part ?

2022-07-06 19:38 UTC, MariamFahmy98 commented
The restore workflow doesn't work as expected. The restoration path sits empty after running the command.
I am still working on it.

2022-07-06 19:38 UTC, jesperpedersen commented
No, just this pull request -- we need restore working again before we can consider merging

2022-07-06 19:48 UTC, MariamFahmy98 commented
I'm kind of lost in the code right now trying to figure out why the restore command isn't working. Can you spot where the problem is?

2022-07-06 20:21 UTC, jesperpedersen requested changes

2022-07-12 15:20 UTC, jesperpedersen commented
```
./pgmoneta-cli -c pgmoneta.conf restore primary latest /tmp
```

doesn't work. `position` is NULL which is valid.

Please, check all the various cases for `restore`

2022-07-12 15:39 UTC, jesperpedersen commented
Ok.

However, the files are still compressed, so something isn't working in the chain

2022-07-12 17:16 UTC, jesperpedersen commented
There are 2 `pgmoneta_delete_file()` in the decompress path...

2022-07-12 20:34 UTC, merged