[pgmoneta#77] Adding a remote backup
pgmoneta/pgmoneta pull request #81
Opened 2022-08-09 11:05 UTC by MariamFahmy98

Creating a backup for a remote server using libssh

2022-08-09 11:22 UTC, MariamFahmy98 commented
Both directories and files are successfully sent to the remote server. However there is an issue when copying files and I am still working on it. Moreover I need to work on the documentation. This is my recent updates.

The CI build fails, however it compiles good locally. Do you have any idea about the problem ? Is it related to github actions ?

2022-08-09 11:50 UTC, jesperpedersen commented
You will likely need to do a proper `cmake/` integration (+ `CMakeLists.txt) and adjust `.github/workflows/ci.yml`

2022-08-09 11:51 UTC, jesperpedersen commented
I would expect local storage to be the first node in the list...

2022-08-09 12:11 UTC, jesperpedersen requested changes

2022-08-09 12:11 UTC, jesperpedersen commented on src/CMakeLists.txt
> +add_compile_options(-lssh)
Follow the other library integrations

2022-08-09 12:11 UTC, jesperpedersen commented on src/CMakeLists.txt
> +find_library(HAVE_SSH NAMES ssh)
Ditto

2022-08-09 12:11 UTC, jesperpedersen commented on src/CMakeLists.txt
> +if (HAVE_SSH)
SSH will be mandatory

2022-08-09 12:11 UTC, jesperpedersen commented on src/include/workflow.h
> +pgmoneta_workflow_create_ssh_storage(void);
Create a `storage.h` with the storage functions. For now, it will include `workflow.h`

2022-08-09 12:11 UTC, jesperpedersen commented on src/libpgmoneta/wf_se_ssh.c
> +/*
Lets rename to `se_ssh.c` -- same for `se_local.c`

2022-08-09 12:11 UTC, jesperpedersen commented on src/libpgmoneta/workflow.c
> -      current->next = pgmoneta_workflow_create_local_storage();
This should be the first node

2022-08-09 13:29 UTC, jesperpedersen commented on src/CMakeLists.txt
> -target_link_libraries(pgmoneta PUBLIC)
?

2022-08-09 13:32 UTC, MariamFahmy98 commented on src/CMakeLists.txt
> -target_link_libraries(pgmoneta PUBLIC)
I have removed it by mistake.

2022-08-09 13:34 UTC, MariamFahmy98 commented
I have a lot of errors similar to this: `undefined reference to ssh_new`

2022-08-09 13:47 UTC, jesperpedersen commented
You will have to look at the includes. Locally I have,

```
rpm -qa | grep ssh | grep devel
libssh2-devel-1.10.0-4.fc36.x86_64
libssh-devel-0.9.6-4.fc36.x86_64

find /usr/include/ -name \*ssh\*.h
/usr/include/libssh/ssh2.h
/usr/include/libssh/libssh_version.h
/usr/include/libssh/libssh.h
/usr/include/libssh2_sftp.h
/usr/include/libssh2.h
/usr/include/libssh2_publickey.h
```

What are the requirements ?

2022-08-09 14:36 UTC, jesperpedersen commented
RHEL 8 says,
```
libssh-devel.i686 : Development files for libssh
libssh-devel.x86_64 : Development files for libssh
```

So, I think version "1" is the way forward...

2022-08-15 11:57 UTC, MariamFahmy98 commented
PTAL

2022-08-15 17:40 UTC, jesperpedersen requested changes

2022-08-15 17:40 UTC, jesperpedersen commented on doc/SSH.md
> +
Lets do

How it works -- backup locally then transfer "remote"

* Prerequisites
* Local / remote sshd
* EC2

2022-08-15 17:40 UTC, jesperpedersen commented on src/include/workflow.h
> +pgmoneta_storage_create_ssh(void);
Move these 2 functions to `storage.h`

2022-08-15 17:40 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +
Sort includes within their group -- leaving `pgmoneta.h` first

2022-08-15 17:40 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +                           "automatically created.\n");
`goto error`

2022-08-15 17:40 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +   pgmoneta_delete_directory(root);
We need to explain when `local` is deleted

... there is the question of the metadata used for commands like `details` ...

2022-08-19 16:49 UTC, jesperpedersen requested changes

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/workflow.c
> +#include "logging.h"
`"` -> `<` + sorting below `<pgmoneta.h>`

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +         goto error;
Missing error log

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +      goto error;
Missing error log

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +      goto error;
Missing error key

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +      printf("%d", rc);
Convert to error log

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +      goto error;
Missing error log

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +      goto error;
Missing error log

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +   rc = sftp_mkdir(sftp, dir, S_IRWXU);
Missing pgmoneta_get_permission call

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +         rc = sftp_mkdir(sftp, dir, S_IRWXU);
Missing pgmoneta_get_permission call

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +               goto error;
Better log error here

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +         goto error;
Better log error here

2022-08-19 16:49 UTC, jesperpedersen commented on src/libpgmoneta/se_ssh.c
> +         goto error;
Better log error here

2022-08-19 19:17 UTC, merged

2022-08-19 19:18 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !