#56 Implement Encryption
pgmoneta/pgmoneta pull request #89
Opened 2022-09-06 18:09 UTC by solokyo

2022-09-06 18:14 UTC, jesperpedersen commented
You need to open an issue with a short description of the work in this pull request, and possible follow-ups.

You can create a checklist in the issue of tasks that needs to be worked on

2022-09-06 18:39 UTC, solokyo commented
Sure, I created an issues page #91

2022-09-06 18:39 UTC, jesperpedersen commented
Ok, so now you can squash and reference #91 from your commit message.

See CONTRIBUTING.md for the commands

2022-09-06 18:41 UTC, jesperpedersen commented
Remember to run `uncrustify` before the next `push -f`

2022-09-06 20:12 UTC, solokyo commented
Please take another look.

2022-09-07 11:36 UTC, jesperpedersen requested changes

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/wf_encryption.c
> +   if (encrypt == true)
Just `if (encrypt)`

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/wf_encryption.c
> +         d = malloc(strlen(to) + 1);
You can use `pgmoneta_append()` here

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/workflow.c
> +   if (config->encryption != ENCRYPTION_NONE)
I don't get a `.zstd.aes` archive

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/aes.c
> +               pgmoneta_log_debug("encrypting from %s to %s", from, to);
Remove this `debug`

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/aes.c
> +   pgmoneta_log_debug("decrypting from %s to %s", from, to);
Remove this `debug`

2022-09-07 11:36 UTC, jesperpedersen commented on src/libpgmoneta/aes.c
> +   pgmoneta_log_info("encrypt_wal:d=%s", d);
Remove this `info`

2022-09-07 11:37 UTC, jesperpedersen commented
The archive feature doesn't encrypt here, using

```
pgmoneta-cli archive primary newest current /tmp
```

2022-09-07 11:39 UTC, jesperpedersen commented
As noted on the issue the documentation is missing.

It is important that `doc/ENCRYPTION.md` describes which algorithms are supported, and why. Plus give the reader an idea of the overhead between `none` and the supported algorithms.

2022-09-07 12:01 UTC, solokyo commented
I will let you know once I finished the modification.

2022-09-08 20:34 UTC, solokyo commented
I pushed doc into a new commit, after we discuss and fix it, I will squash it with the previous commit.

2022-09-08 21:50 UTC, jesperpedersen requested changes

2022-09-08 21:50 UTC, jesperpedersen commented on doc/ENCRYPTION.md
> +Longer the key length, safer the encryption. However, with 20% (192 bit) and 40 (256 bit) extra workload compare to 128 bit.
40 -> 40%

2022-09-08 21:50 UTC, jesperpedersen commented on doc/ENCRYPTION.md
> +
I would list the available options here as well, and highlight that `aes` is `aes-256-cbc`

2022-09-08 21:50 UTC, jesperpedersen commented on doc/man/pgmoneta.conf.5.rst
> +  The encryption mode. Default is none
Copy the description from CONFIGURATION.md without the formatting

2022-09-08 21:51 UTC, jesperpedersen commented
You will need

* README.md: AES encryption support
* AUTHORS: Your name and email

2022-09-08 21:52 UTC, jesperpedersen commented
Rebase and squash as well

2022-09-08 21:57 UTC, jesperpedersen commented
Note, that archive would benefit from a `pgmoneta-cli decrypt <file>` command. This could be a separate pull request

2022-09-09 12:02 UTC, jesperpedersen commented
Merged with a few modifications.

Thanks for your contribution !

2022-09-09 12:02 UTC, closed without merging